### ISSUE TITLE
Help images are not displayed

### ISSUE THREAD

**Issue by protegh** [fritteli/gentoo-overlay#12]
Same as in https://gitlab.com/gitlab-org/gitlab-ce/issues/765 where a fix for an arch linux PKGBUILD is provided in https://github.com/rumpelsepp/gitlab-pkgbuilds/commit/68937d754bb98dbd8cd03991df59f2e65f7b51c7

It should be easy to add something similar to the Ebuild.

**Comment by fritteli** [comment]
What version are you using?

**Comment by fritteli** [comment]
This issue is very old and affects an outdated version of gitlabhq. I will therefore close it. If it still appears in the latest version (7.13.1 as of 2015-07-25), please open a new issue.

**Comment by protegh** [comment]
In April I had version 7.8.1 and the issue was fixed with version 7.12.1 already.
