### ISSUE TITLE
www-apps/gitlabhq-7.9.3: Bad sed expression

### ISSUE THREAD

**Issue by mr-hands** [fritteli/gentoo-overlay#18]
You have a sed call

sed -i -E \
                -e 's|(username:).*|\1 gitlab|' \
                -e 's|(password:).*|\1 gitlab|' \
                -e 's|(socket:).*|/run/postgresql/.s.PGSQL.5432|'

that misses ``\1''  at the last expression.

**Comment by fritteli** [comment]
Fixed in the latest version of the 7.10.4 ebuild. Please test.
