### ISSUE TITLE
Add kerberos USE flag for >=www-apps/gitlabhq-7.11

### ISSUE THREAD

**Issue by xificurk** [fritteli/gentoo-overlay#20]
If I read this well, Gitlab 7.11 and higher does not have a hard-coded kerberos dependency (see gitlabhq/gitlabhq#8799).
Could you please add new kerberos USE flag to those ebuilds, so that gitlabhq could be installed with(out) kerberos support?

**Comment by fritteli** [comment]
I'm planning to add the USE flag to gitlabhq-7.12.

**Comment by xificurk** [comment]
I consider this resolved, thank you.
