### ISSUE TITLE
gitlab-7.13.2 emerge failed

### ISSUE THREAD

**Issue by Kami-no** [fritteli/gentoo-overlay#22]
compiling rugged_patch.c
linking shared-object rugged/rugged.so
/var/tmp/portage/www-apps/gitlabhq-7.13.2/image/opt/gitlab/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2/ext/rugged/../../vendor/libgit2/build/libgit2.a(http.c.o): In function `clear_parser_state':
/var/tmp/portage/www-apps/gitlabhq-7.13.2/image/opt/gitlab/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2/vendor/libgit2/src/transports/http.c:479: undefined reference to `http_parser_init'
/var/tmp/portage/www-apps/gitlabhq-7.13.2/image/opt/gitlab/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2/ext/rugged/../../vendor/libgit2/build/libgit2.a(http.c.o): In function `http_connect':
/var/tmp/portage/www-apps/gitlabhq-7.13.2/image/opt/gitlab/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2/vendor/libgit2/src/transports/http.c:537: undefined reference to `http_should_keep_alive'
/var/tmp/portage/www-apps/gitlabhq-7.13.2/image/opt/gitlab/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2/ext/rugged/../../vendor/libgit2/build/libgit2.a(http.c.o): In function `http_stream_read':
/var/tmp/portage/www-apps/gitlabhq-7.13.2/image/opt/gitlab/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2/vendor/libgit2/src/transports/http.c:678: undefined reference to `http_parser_execute'
/var/tmp/portage/www-apps/gitlabhq-7.13.2/image/opt/gitlab/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2/vendor/libgit2/src/transports/http.c:700: undefined reference to `http_errno_description'
/var/tmp/portage/www-apps/gitlabhq-7.13.2/image/opt/gitlab/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2/ext/rugged/../../vendor/libgit2/build/libgit2.a(netops.c.o): In function `gitno_extract_url_parts':
/var/tmp/portage/www-apps/gitlabhq-7.13.2/image/opt/gitlab/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2/vendor/libgit2/src/netops.c:239: undefined reference to `http_parser_parse_url'
collect2: error: ld returned 1 exit status
Makefile:231: recipe for target 'rugged.so' failed
make: *** [rugged.so] Error 1

make failed, exit code 2

Gem files will remain installed in /var/tmp/portage/www-apps/gitlabhq-7.13.2/image/opt/gitlab/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2 for inspection.
Results logged to /var/tmp/portage/www-apps/gitlabhq-7.13.2/image/opt/gitlab/vendor/bundle/ruby/2.0.0/extensions/x86_64-linux/2.0.0/rugged-0.22.2/gem_make.out
An error occurred while installing rugged (0.22.2), and Bundler cannot continue.
Make sure that `gem install rugged -v '0.22.2'` succeeds before bundling.

**Comment by fritteli** [comment]
Hm, weird, I had no problems building it. Can you post the output of `emerge --info`?
And what versions of `dev-lang/ruby` and `dev-ruby/rubygems` have you got installed?

**Comment by Kami-no** [comment]
I used default RUBY_TARGETS="ruby19 ruby20".
dev-lang/ruby-2.0.0_p645 and 1.9.3_p551-r1
dev-ruby/rubygems-2.2.5.r1

Set RUBY_TARGETS="ruby21" and... nothing changed.

**Comment by LucaFulchir** [comment]
Same problem here.  
solved by installing net-libs/http-parser, dev-libs/libgit2 (>=0.22)  
then running emerge with

    RUGGED_USE_SYSTEM_LIBRARIES="YES" emerge --ask gitlabhq

as you can guess it uses system libraries for "rugged" only.
It's only a workaround (I had to look in the rugged makefile...) but it seems to work for now...

**Comment by Kami-no** [comment]
Confirm, it helps. Ebuild tuning required.

**Comment by fritteli** [comment]
Okay, thanks for investigating. I'm planning to add ebuilds for version 7.13.4 and I'll try to incorporate a fix there.

**Comment by fritteli** [comment]
Hello all,
can you try the new ebuild version 7.13.4 with the use flag "rugged_use_system_libraries"? I tried to appy the suggested fix, but couldn't test it myself.

Hope it helps. If so, you may close the issue.

**Comment by fritteli** [comment]
Okay, now i encountered the same build error with 7.13.4, and setting the aforementioned USE flag fixed that. So i consider this issue closed.
