### ISSUE TITLE
www-apps/gitlabhq: Missing archive_repo sidekiq queue in ebuild

### ISSUE THREAD

**Issue by theridane** [fritteli/gentoo-overlay#23]
Gitlab 7.10 introduced a new sidekiq queue that handles ZIP generation. Without it, an attempt at downloading a repo ZIP ends in an endless HTTP 302 redirect loop.
Should I fix the ebuilds (in a pull rq) without renaming or should I make -r1 versions?

**Comment by fritteli** [comment]
hi theridane

thanks for offering your support. just fix the ebuild, you don't need to create an -r1 version.

thanks,
fritteli

**Comment by fritteli** [comment]
I merged your PR, thanks for the contribution!
I also re-generated the Manifest, so everything should work now.
