### ISSUE TITLE
www-apps/gitlab-ce: Correct the message after update/installation of ebuild

### ISSUE THREAD

**Issue by Kami-no** [fritteli/gentoo-overlay#28]
* 4. Finally execute the following command to initlize environment:
 *        emerge --config "=www-apps/gitlab-ce-8.2.0"

This command should be done even after update.

**Comment by fritteli** [comment]
You're right. I'll change the postinst message in version 8.2.1 of gitlab-ce. I'll push that later today.

**Comment by fritteli** [comment]
I just pushed the new ebuild (www-apps/gitlab-ce-8.2.1) with the updated postinst message.

I'm now closing this bug, if you don't think that the message is now appropriate, please re-open.
