### ISSUE TITLE
mail_room does not exit

### ISSUE THREAD

**Issue by g0dsCookie** [fritteli/gentoo-overlay#29]
Hello,

when trying to stop the gitlab service, the mail_room process won't be stopped as shown below.

**service gitlab stop**
 * Stopping GitLab - mail_room ...                                                                                                                                                                                                     [ ok ]
 * Stopping GitLab - Sidekiq ...                                                                                                                                                                                                       [ ok ]
 * Stopping GitLab - Unicorn servers ...                                                                                                                                                                                          [ ok ]

**ps axfu | grep [m]ail_room**
git      12668 22.0  1.5 655652 245752 ?       Ssl  20:05   0:09 ruby21 /opt/gitlab/vendor/bundle/ruby/2.1.0/bin/mail_room -q -c /etc/gitlab/mail_room.yml >> /var/log/gitlab/mail_room.log 2>&1

**Comment by fritteli** [comment]
Thanks for reporting this. Since I haven't set up mail_room for my GitLab instance, I never noticed this. I'll look into it as soon as I find the time. Meanwhile, if you find a solution, I'm happy to accept pull requests :smile:

**Comment by fritteli** [comment]
Great, thanks for helping me! I merged your pull request, the issue should be fixed for all new installs.
