### ISSUE TITLE
www-apps/gitlabhq-8.1.4

### ISSUE THREAD

**Issue by dummys** [fritteli/gentoo-overlay#31]
Hi,
Got this error after installation:

gaia gitlabhq-8.1 # /etc/init.d/gitlabhq-8.1 restart
 * /opt/gitlabhq-8.1/tmp/pids: creating directory
 * /opt/gitlabhq-8.1/tmp/pids: correcting owner
 * Starting GitLab 8.1 Unicorn servers ...
bundler: command not found: unicorn_rails
Install missing gem executables with `bundle install`
 * start-stop-daemon: failed to start `/usr/bin/bundle'                                           [ !! ]
 * Starting GitLab 8.1 Sidekiq ...
bundler: command not found: sidekiq
Install missing gem executables with `bundle install`                                             [ !! ]
 * Starting GitLab 8.1 Workhorse ...                  

Tried at sudo -u git -H bundle install in the /opt/gitlabhq directory and get:

Installing rake 10.4.2
Installing CFPropertyList 2.3.1
Installing RedCloth 4.2.9 with native extensions
Installing ace-rails-ap 2.0.1
Installing i18n 0.7.0
Installing json 1.8.3 with native extensions
Installing minitest 5.7.0
Installing thread_safe 0.3.5
Installing builder 3.2.2
Installing erubis 2.7.0
Installing rack 1.5.5
Installing mime-types 1.25.1
Installing arel 5.0.1.20140414130214
Installing activerecord-deprecated_finders 1.0.4
Installing thor 0.19.1
Installing addressable 2.3.8
Using bundler 1.11.2
Installing hike 1.2.3
Installing multi_json 1.11.2
Installing tilt 1.4.1
Installing asciidoctor 1.5.2
Installing encryptor 1.3.0
Installing attr_required 1.0.0
Installing execjs 2.6.0
Installing ice_nine 0.11.1
Installing bcrypt 3.1.10 with native extensions
Installing sass 3.2.19
Installing browser 1.0.0
Installing cal-heatmap-rails 0.0.1
Installing hitimes 1.2.3 with native extensions
Installing charlock_holmes 0.6.9.4 with native extensions
Installing chunky_png 1.3.4
Installing coffee-script-source 1.9.1.1
Installing colored 1.2
Installing colorize 0.5.8
Installing connection_pool 2.2.0
Installing safe_yaml 1.0.4
Installing creole 0.3.8
Installing orm_adapter 0.5.0
Installing rotp 2.1.1
Installing diff-lcs 1.2.5
Installing diffy 3.0.7
Installing email_reply_parser 0.5.8
Installing equalizer 0.0.11
Installing escape_utils 0.2.4 with native extensions
Installing eventmachine 1.0.8 with native extensions
Installing excon 0.45.4
Installing expression_parser 0.9.0
Installing multipart-post 2.0.0
Installing multi_xml 0.5.5
Installing formatador 0.2.5
Installing net-ssh 2.9.2
Installing inflecto 0.0.2
Installing mini_portile 0.6.2
Installing ipaddress 0.8.0
Installing trollop 2.1.2
Installing rugged 0.22.2 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby20 extconf.rb
checking for gmake... yes
checking for cmake... yes
checking for pkg-config... yes
 -- cmake .. -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "Unix Makefiles"
 -- /usr/bin/gmake
checking for main() in -lgit2... yes
checking for git2.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling rugged_tag_collection.c
compiling rugged_remote_collection.c
compiling rugged_diff_delta.c
compiling rugged_index.c
compiling rugged_remote.c
compiling rugged_diff.c
compiling rugged_revwalk.c
compiling rugged_signature.c
compiling rugged_diff_hunk.c
compiling rugged_branch_collection.c
compiling rugged_submodule.c
compiling rugged_commit.c
compiling rugged_backend.c
compiling rugged_note.c
compiling rugged_blob.c
compiling rugged_reference_collection.c
compiling rugged.c
compiling rugged_submodule_collection.c
compiling rugged_reference.c
compiling rugged_patch.c
compiling rugged_diff_line.c
compiling rugged_blame.c
compiling rugged_tag.c
compiling rugged_repo.c
compiling rugged_settings.c
compiling rugged_cred.c
compiling rugged_tree.c
compiling rugged_object.c
compiling rugged_branch.c
compiling rugged_config.c
linking shared-object rugged/rugged.so
/opt/gitlabhq-8.1/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2/ext/rugged/../../vendor/libgit2/build/libgit2.a(http.c.o): In function `clear_parser_state':
/opt/gitlabhq-8.1/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2/vendor/libgit2/src/transports/http.c:479: undefined reference to `http_parser_init'
/opt/gitlabhq-8.1/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2/ext/rugged/../../vendor/libgit2/build/libgit2.a(http.c.o): In function `http_connect':
/opt/gitlabhq-8.1/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2/vendor/libgit2/src/transports/http.c:537: undefined reference to `http_should_keep_alive'
/opt/gitlabhq-8.1/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2/ext/rugged/../../vendor/libgit2/build/libgit2.a(http.c.o): In function `http_stream_read':
/opt/gitlabhq-8.1/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2/vendor/libgit2/src/transports/http.c:678: undefined reference to `http_parser_execute'
/opt/gitlabhq-8.1/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2/vendor/libgit2/src/transports/http.c:700: undefined reference to `http_errno_description'
/opt/gitlabhq-8.1/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2/ext/rugged/../../vendor/libgit2/build/libgit2.a(netops.c.o): In function `gitno_extract_url_parts':
/opt/gitlabhq-8.1/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2/vendor/libgit2/src/netops.c:239: undefined reference to `http_parser_parse_url'
collect2: error: ld returned 1 exit status
Makefile:231: recipe for target 'rugged.so' failed
make: *** [rugged.so] Error 1

make failed, exit code 2

Gem files will remain installed in /opt/gitlabhq-8.1/vendor/bundle/ruby/2.0.0/gems/rugged-0.22.2 for inspection.
Results logged to /opt/gitlabhq-8.1/vendor/bundle/ruby/2.0.0/extensions/x86_64-linux/2.0.0/rugged-0.22.2/gem_make.out
Installing get_process_mem 0.2.0
Installing github-markup 1.3.3
Installing posix-spawn 0.3.11 with native extensions
Installing gitlab_meta 7.0
Installing net-ldap 0.11
Installing hashie 3.4.2
Installing pyu-ruby-sasl 0.0.3.3
Installing rubyntlm 0.5.2
Installing rouge 1.10.1
Installing stringex 2.5.2
Installing sexp_processor 4.6.0
Installing mimemagic 0.3.0
Installing http_parser.rb 0.5.3 with native extensions
Installing httpclient 2.6.0.1
Installing ice_cube 0.11.1
Installing jquery-atwho-rails 1.0.1
Installing jwt 1.5.1
Installing kgio 2.9.3 with native extensions
Installing systemu 2.6.5
Installing mail_room 0.6.1
Installing mousetrap-rails 1.4.6
Installing mysql2 0.3.20 with native extensions
Installing nested_form 0.3.2
Installing newrelic_rpm 3.9.4.245
Installing nprogress-rails 0.1.2.3
Installing oauth 0.4.7
Installing timfel-krb5-auth 0.8.3 with native extensions
Installing rubypants 0.2.0
Installing rack-cors 0.4.0
Installing raindrops 0.15.0 with native extensions
Installing raphael-rails 2.1.2
Installing redcarpet 3.3.3 with native extensions
Installing redis 3.2.1
Installing request_store 1.2.0
Installing rinku 1.7.3 with native extensions
Installing settingslogic 2.0.9
Installing simple_oauth 0.1.9
Installing six 0.2.0
Installing slack-notifier 1.2.1
Installing stamp 0.5.0
Installing state_machine 1.2.0
Installing underscore-rails 1.4.4
Installing unf_ext 0.0.7.1 with native extensions
Installing version_sorter 2.0.0 with native extensions
Installing fission 0.5.0
Installing gemojione 2.0.1
Installing rdoc 3.12.2
Installing tzinfo 1.2.2
Installing descendants_tracker 0.0.4
Installing rack-test 0.6.3
Installing warden 1.2.3
Installing rack-accept 0.4.5
Installing rack-mount 0.8.3
Installing rack-attack 4.3.0
Installing rack-protection 1.5.3
Installing mail 2.6.3
Installing select2-rails 3.5.9.3
Installing sprockets 2.12.4
Installing haml 4.0.7
Installing attr_encrypted 1.3.4
Installing autoprefixer-rails 5.2.1.2
Installing uglifier 2.7.2
Installing timers 4.0.4
Installing rqrcode 0.7.0
Installing coffee-script 2.4.1
Installing crack 0.4.2
Installing gitlab-linguist 3.0.1
Installing faraday 0.9.2
Installing httparty 0.13.5
Installing net-scp 1.2.1
Installing nokogiri 1.6.6.2 with native extensions
An error occurred while installing rugged (0.22.2), and Bundler cannot continue.
Make sure that `gem install rugged -v '0.22.2'` succeeds before bundling.

**Comment by fritteli** [comment]
I'm sorry, but are you sure you installed the ebuild from this overlay? Because, an ebuild `www-apps/gitlabhq-8.1.4` doesn't exist here. `gitlabhq` has long been renamed to `gitlab-ce`. The init script is called `/etc/init.d/gitlab` and Gitlab is installed under `/opt/gitlab`.
Besides, there's now version 8.3.2 available here. So I guess that either you used another overlay, or you haven't updated this one in a long time. Anyway, try upgrading to the latest version.

**Comment by dummys** [comment]
dummys@gaia ~ $ layman -l

 * gitlab                    [Git       ] (https://gitlab.awesome-it.de/overlays/gitlab...)


It's not yours ?

**Comment by fritteli** [comment]
Nope, sorry. Mine is https://github.com/fritteli/gentoo-overlay.git or https://gittr.ch/linux/gentoo-overlay.git. So I won't be able to help you, unfortunately.

Therefore closing the issue.

**Comment by fritteli** [comment]
You may try opening an issue here: https://gitlab.awesome-it.de/overlays/gitlab/issues
