### ISSUE TITLE
dev-vcs/gitlab-workhorse-0.6.4: Cannot find $EPATCH_SOURCE!

### ISSUE THREAD

**Issue by Kami-no** [fritteli/gentoo-overlay#32]
* Messages for package dev-vcs/gitlab-workhorse-0.6.4:

 * Cannot find $EPATCH_SOURCE!  Value for $EPATCH_SOURCE is:
 *
 *   /var/lib/layman/fritteli/dev-vcs/gitlab-workhorse/files/fix-Makefile-0.6.4.patch
 *   ( fix-Makefile-0.6.4.patch )
 * ERROR: dev-vcs/gitlab-workhorse-0.6.4::fritteli failed (prepare phase):
 *   Cannot find $EPATCH_SOURCE!
 *
 * Call stack:
 *     ebuild.sh, line  133:  Called src_prepare
 *   environment, line 2278:  Called epatch '/var/lib/layman/fritteli/dev-vcs/gitlab-workhorse/files/fix-Makefile-0.6.4.patch'
 *   environment, line  855:  Called die
 * The specific snippet of code:
 *                   die "Cannot find \$EPATCH_SOURCE!";
 *
 * If you need support, post the output of `emerge --info '=dev-vcs/gitlab-workhorse-0.6.4::fritteli'`,
 * the complete build log and the output of `emerge -pqv '=dev-vcs/gitlab-workhorse-0.6.4::fritteli'`.
 * The complete build log is located at '/var/tmp/portage/dev-vcs/gitlab-workhorse-0.6.4/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-vcs/gitlab-workhorse-0.6.4/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-vcs/gitlab-workhorse-0.6.4/work/gitlab-workhorse-0.6.4-3f8da4ae570ca6e79c795f343dad278d60edd343'
 * S: '/var/tmp/portage/dev-vcs/gitlab-workhorse-0.6.4/work/gitlab-workhorse-0.6.4-3f8da4ae570ca6e79c795f343dad278d60edd343'
 *
 * The following package has failed to build, install, or execute postinst:
 *
 *  (dev-vcs/gitlab-workhorse-0.6.4:0/0::fritteli, ebuild scheduled for merge), Log file:
 *   '/var/tmp/portage/dev-vcs/gitlab-workhorse-0.6.4/temp/build.log'
 *

**Comment by fritteli** [comment]
Ouch, I'm sorry. I'll fix it right away.

**Comment by fritteli** [comment]
fixed. thanks a bunch for reporting it.
