### ISSUE TITLE
gitlab v8.10.2

### ISSUE THREAD

**Issue by Kami-no** [fritteli/gentoo-overlay#38]
avalon ~ # emerge --config gitlab-ce

Configuring pkg...

 * Checking configuration files
 * Migrating database ...
   /usr/bin/ruby /usr/bin/bundle exec rake db:migrate RAILS_ENV=production
rake aborted!

**Errno::ENOENT: No such file or directory @ realpath_rec - /home/git**
/opt/gitlab/config/initializers/6_validations.rb:6:in `realpath'
/opt/gitlab/config/initializers/6_validations.rb:6:in `realpath'
/opt/gitlab/config/initializers/6_validations.rb:6:in `find_parent_path'
/opt/gitlab/config/initializers/6_validations.rb:22:in `block in validate_storages'
/opt/gitlab/config/initializers/6_validations.rb:19:in `each'
/opt/gitlab/config/initializers/6_validations.rb:19:in `validate_storages'
/opt/gitlab/config/initializers/6_validations.rb:29:in `<top (required)>'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:268:in `load'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:268:in `block in load'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:268:in `load'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7/lib/rails/engine.rb:652:in `block in load_config_initializer'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7/lib/active_support/notifications.rb:166:in `instrument'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7/lib/rails/engine.rb:651:in `load_config_initializer'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7/lib/rails/engine.rb:615:in `each'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7/lib/rails/engine.rb:615:in `block in <class:Engine>'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7/lib/rails/initializable.rb:30:in `instance_exec'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7/lib/rails/initializable.rb:30:in `run'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7/lib/rails/initializable.rb:44:in `each'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7/lib/rails/initializable.rb:44:in `tsort_each_child'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7/lib/rails/initializable.rb:54:in `run_initializers'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7/lib/rails/application.rb:352:in `initialize!'
/opt/gitlab/config/environment.rb:5:in `<top (required)>'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:274:in `require'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:274:in `block in require'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7/lib/active_support/dependencies.rb:274:in `require'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7/lib/rails/application.rb:328:in `require_environment!'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
 * ERROR: www-apps/gitlab-ce-8.10.2::fritteli failed (config phase):
 *   failed to run rake db:migrate
 *
 * Call stack:
 *     ebuild.sh, line  133:  Called pkg_config
 *   environment, line 4217:  Called exec_rake 'db:migrate'
 *   environment, line 1850:  Called die
 * The specific snippet of code:
 *   		${command}" || die "failed to run rake $@"
 *
 * If you need support, post the output of `emerge --info '=www-apps/gitlab-ce-8.10.2::fritteli'`,
 * the complete build log and the output of `emerge -pqv '=www-apps/gitlab-ce-8.10.2::fritteli'`.
!!! When you file a bug report, please include the following information:
GENTOO_VM=  CLASSPATH="" JAVA_HOME="/etc/java-config-2/current-system-vm"
JAVACFLAGS="" COMPILER=""
and of course, the output of emerge --info =gitlab-ce-8.10.2
 * The complete build log is located at '/var/tmp/portage/www-apps/gitlab-ce-8.10.2/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/www-apps/gitlab-ce-8.10.2/temp/environment'.
 * Working directory: '/usr/lib64/python3.4/site-packages'
 * S: '/var/tmp/portage/www-apps/gitlab-ce-8.10.2/work/gitlab-ce-8.10.2'

**Comment by fritteli** [comment]
Gitlab 8.10 has considerably changed the configuration. Have you checked that the path to the repository in gitlab.yml is correct?

If `grep home/git /etc/gitlab/gitlab.yml`gives you a result, then you need to adjust the path, probably to `/var/lib/git/repositories/`.

Did that do the trick?

**Comment by Kami-no** [comment]
It fixes the bug...

**Comment by fritteli** [comment]
Okay, that's good. But it shows me that perhaps the ebuild should take care of that config change. After all, the path will always be `/var/lib/git/repositories/` and never `/home/git`. Maybe I'll add a patch to future ebuilds.
Thanks for reporting!
