### ISSUE TITLE
Sidekiq never sends mails (they pile up as background jobs)

### ISSUE THREAD

**Issue by typingArtist** [fritteli/gentoo-overlay#39]
It appears your repo has not caught up with latest gitlab-sidekiq.service changes. The one provided still instructs sidekiq to watch out for jobs in the ‘mailer’ queue instead of the ‘mailers’ queue. Seems there is an [issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/4276) for it available which [has already been fixed](https://gitlab.com/gitlab-org/gitlab-recipes/blob/master/init/systemd/gitlab-sidekiq.service). Would it make sense to grab the officially maintained service file instead of having it in the overlay?

```diff
--- gitlab-sidekiq.service.orig 2016-08-10 11:54:45.000000000 +0200
+++ gitlab-sidekiq.service      2016-08-10 10:56:59.000000000 +0200
@@ -20,7 +20,7 @@
 SyslogIdentifier=gitlab-sidekiq
 PIDFile=/run/gitlab/sidekiq.pid

-ExecStart=/usr/bin/bundle exec "sidekiq -d -q archive_repo -q post_receive -q mailer -q system_hook -q project_web_hook -q gitlab_shell -q common -q default -e production -P /run/gitlab/sidekiq.pid -d -L /var/log/gitlab/sidekiq.log >> /var/log/gitlab/sidekiq.log 2>&1"
+ExecStart=/usr/bin/bundle exec "sidekiq -d -q archive_repo -q post_receive -q mailers -q system_hook -q project_web_hook -q gitlab_shell -q common -q default -e production -P /run/gitlab/sidekiq.pid -d -L /var/log/gitlab/sidekiq.log >> /var/log/gitlab/sidekiq.log 2>&1"
 ExecStop=/usr/bin/bundle exec "sidekiqctl stop /run/gitlab/sidekiq.pid >> /var/log/gitlab/sidekiq.log 2>&1"
```

Do emails work for you without that patch?

**Comment by fritteli** [comment]
Thanks for the report, and sorry for the long delay.
I'll fix it ASAP. Using the provided service files certainly makes sense, I'll look into that.

**Comment by typingArtist** [comment]
BTW, I don’t like the GitLab systemd scripts anyway. All of them try to daemonize around the systemd approach, just like in the init.d age. Instead, they should call the script without daemonization and let systemd handle restart and stop.
