### ISSUE TITLE
gitlab-shell-2.0.1 An unexpected error occurred (redis-cli returned 1).

### ISSUE THREAD

**Issue by Kami-no** [fritteli/gentoo-overlay#4]
$ git push
Counting objects: 7, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 475 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
**remote: GitLab: An unexpected error occurred (redis-cli returned 1).**
To git@git.local:root/quest.git
   348cf92..f144201  dev -> dev

To fix it you need in /etc/gitlab-shell.yml comment the line

socket: /var/run/redis/redis.sock # Comment out this line if you want to use TCP

BTW it was even in older versions.

**Comment by ckibuchi** [comment]
where can I find gitlab-shell.yml in fedora 20?

**Comment by Kami-no** [comment]
Try this:
find / -name gitlab-shell.yml

Never tried Gitlab with Fedora 20. This is a 'repository' for Gentoo, don't think you'll get a Fedora-specific support here.
