### ISSUE TITLE
Gitlab: .secret file gone

### ISSUE THREAD

**Issue by Kami-no** [fritteli/gentoo-overlay#41]
After upgrade from 8.10 to 8.11 file .secret has gone.

Update from 8.11.0 to  8.11.1 planed to wipe DB with:
/usr/bin/ruby /usr/bin/bundle exec rake db:setup RAILS_ENV=production

Touched /opt/gitlab/.secret

Successfully upgraded. But file .secret has gone.

Same during upgrade from 8.11.1 to 8.11.2 - touched file has gone away again (but ebuild require it for upgrade or it'll wipe DB).

**Comment by fritteli** [comment]
Right ... I noticed that, too. Have you got any idea how I can determine whether it is a fresh install or an upgrade? Is there another file I could check for? Or does perhaps the ebuild provide a method for doing that? I'll have to look into that. If you've got any idea, I'm happy if you share it here!

**Comment by Kami-no** [comment]
1. Ask user like it happens for db:setup
2. Based on setup/migrate procedure - it creates cache for assets even after upgrade in dir /opt/gitlab/public/assets (not sure 100%)
3. Based on script that checks if migration required (sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production)

**Comment by fritteli** [comment]
Please test the new ebuild for version 8.11.4: This one now checks for the existence of the .git directory within /opt/gitlab; that directory is created during the config run, so it should be safe. It worked on my server, anyway.

If it works for you, feel free to close the issue. Thanks for reporting!

**Comment by Kami-no** [comment]
Fixed
