### ISSUE TITLE
GitLab 8.15.4 sidekiq & unicorn /home/git error

### ISSUE THREAD

**Issue by Kami-no** [fritteli/gentoo-overlay#42]
At start fro unicorn and sidekiq
```
/opt/gitlab/config/initializers/6_validations.rb:6:in `realpath': No such file or directory @ realpath_rec - /home/git
```

**Comment by Kami-no** [comment]
# emerge --config gitlab-ce


Configuring pkg...

 * Checking configuration files
 * Migrating database ...
   /usr/bin/ruby /usr/bin/bundle exec rake db:migrate RAILS_ENV=production
D, [2017-01-17T16:08:12.850694 #18424] DEBUG -- sentry: ** [Raven] No such file or directory @ realpath_rec - /home/git excluded from capture due to environment or should_capture callback
rake aborted!
Errno::ENOENT: No such file or directory @ realpath_rec - /home/git
/opt/gitlab/config/initializers/6_validations.rb:6:in `realpath'
/opt/gitlab/config/initializers/6_validations.rb:6:in `realpath'
/opt/gitlab/config/initializers/6_validations.rb:6:in `find_parent_path'
/opt/gitlab/config/initializers/6_validations.rb:22:in `block in validate_storages'
/opt/gitlab/config/initializers/6_validations.rb:19:in `each'
/opt/gitlab/config/initializers/6_validations.rb:19:in `validate_storages'
/opt/gitlab/config/initializers/6_validations.rb:29:in `<top (required)>'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/opt/gitlab/config/environment.rb:5:in `<top (required)>'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
/opt/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
 * ERROR: www-apps/gitlab-ce-8.15.4::fritteli failed (config phase):
 *   failed to run rake db:migrate
 * 
 * Call stack:
 *     ebuild.sh, line  115:  Called pkg_config
 *   environment, line 4253:  Called exec_rake 'db:migrate'
 *   environment, line 1861:  Called die
 * The specific snippet of code:
 *   		${command}" || die "failed to run rake $@"
 * 
 * If you need support, post the output of `emerge --info '=www-apps/gitlab-ce-8.15.4::fritteli'`,
 * the complete build log and the output of `emerge -pqv '=www-apps/gitlab-ce-8.15.4::fritteli'`.
!!! When you file a bug report, please include the following information:
GENTOO_VM=  CLASSPATH="" JAVA_HOME="/etc/java-config-2/current-system-vm"
JAVACFLAGS="" COMPILER=""
and of course, the output of emerge --info =gitlab-ce-8.15.4
 * The complete build log is located at '/var/tmp/portage/www-apps/gitlab-ce-8.15.4/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/www-apps/gitlab-ce-8.15.4/temp/environment'.
 * Working directory: '/usr/lib64/python3.4/site-packages'
 * S: '/var/tmp/portage/www-apps/gitlab-ce-8.15.4/work/gitlab-ce-8.15.4

**Comment by Kami-no** [comment]
created
ln -s /var/lib/git/repositories /opt/gitlab/
ln -s /opt/gitlab /home/git

**Comment by fritteli** [comment]
I'm sorry I haven't responded earlier. We just got our second child, so my priorities currently lie with changing diapers rather than fixing the ebuild :)
I have to say, though, that I never had this error. Meanwhile v8.16.4 is out, perhaps I'll jump straight to that.

**Comment by fritteli** [comment]
I cannot reproduce this problem.
What home dir does your gitlab user (``git``) have? It should be ``/var/lib/git``. To verify, use this command (as root):
``grep git /etc/passwd``
It should give something like this:
``git:x:200:481:added by portage for gitlab-shell:/var/lib/git:/bin/bash``
If it says ``/home/git`` instead of ``/var/lib/git``, then something is wrong.

Also, check the option ``working_directory`` in /etc/gitlab/unicorn.rb. It should point to ``/opt/gitab``.
In /etc/gitlab.yml, check the setting for repositories.storages.default (in my config file, it's on line 457). It should point to ``/var/lib/git/repositories``.
Are you using Mailroom? I'm not, so there might be a difference, too.

Can you post the output of
``grep -R /home/git /etc/gitlab``
?

**Comment by Kami-no** [comment]
```
# grep git /etc/passwd
git:x:112:993:added by portage for gitlab-shell:/var/lib/git:/bin/bash
# grep -R /home/git /etc/gitlab
/etc/gitlab/gitlab.yml:      default: /home/git/repositories/
/etc/gitlab/gitlab.yml:    # secret_file: /home/git/gitlab/.gitlab_shell_secret
```
New release changed the gitlab.yml for some reason =(
