### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by samuelbernardo** [fritteli/gentoo-overlay#43]
Hi,
Since your overlay is not registered in gentoo overlays, I suggests an update to your readme with repos.conf configuration for your overlay.
https://wiki.gentoo.org/wiki//etc/portage/repos.conf

Here is how I configured it (/etc/portage/repos.conf/fritteli.conf):

[fritteli]
location = /var/db/repos/fritteli
sync-type = git
sync-uri = https://github.com/fritteli/gentoo-overlay.git
auto-sync = yes

This way I'm using your overlay as a repository, that take advantage of only need emerge to update (layman is not necessary).

**Comment by fritteli** [comment]
Thanks for the hint. I'll do that (soon).

**Comment by fritteli** [comment]
Done.
