### ISSUE TITLE
GitLab 9.0 requires Ruby 2.3

### ISSUE THREAD

**Issue by xificurk** [fritteli/gentoo-overlay#44]
GitLab 9.0 dropped support for Ruby 2.1, Ruby 2.3 is required now.

Current ebuilds allows installation with ruby21, but database migrations fail.

For more info see:
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/install/installation.md#2-ruby

**Comment by fritteli** [comment]
Ugh ... thanks for reporting! I'll fix that asap.

**Comment by fritteli** [comment]
Done. Thanks again for notifying me of this change.

**Comment by xificurk** [comment]
Thank you prompt resolution.
