### ISSUE TITLE
Impossible to install gitlab-gitaly

### ISSUE THREAD

**Issue by alcad** [fritteli/gentoo-overlay#49]
Hi Fritteli,
i've got a trouble with update of gitlab.
Gitaly cannot install and I receive this error:
```
>>> Install gitlab-gitaly-0.38.0-r1 into /var/tmp/portage/www-servers/gitlab-gitaly-0.38.0-r1/image/ category www-servers
chmod: cannot access '/var/tmp/portage/www-servers/gitlab-gitaly-0.38.0-r1/image//var/lib/gitlab-gitaly/ruby/bin/*': No such file or directory
 * ERROR: www-servers/gitlab-gitaly-0.38.0-r1::fritteli failed (install phase):
 *   fperms failed
```
It seems a path typo.
Can you check please?
Regards

**Comment by mkconel** [comment]
Here is a quick fix for this issue if you have not figured it already.

1. Find your `gitlab-gitaly` Ebuild directory (ex. `/usr/local/portage/overlays/fritteli/www-servers/gitlab-gitaly/`) and go to it.
2. Open gitaly Ebuild file (ex. `gitlab-gitaly-0.38.0-r1.ebuild`).
3. Comment out the line `fperms 0755 /var/lib/gitlab-gitaly/ruby/bin/*` (line 38) and save the file.
4. Run Repoman to regenerate manifest file `repoman manifest` (if you don't have it, merge `app-portage/repoman` package).
5. Try merging gitlab and/or gitaly again. 
6. After successful installation, fix permissions yourself `chmod +x /var/lib/gitlab-gitaly/ruby/bin/*`.

**Comment by alcad** [comment]
Thank you @mkconel your workaround worked like a charm.

**Comment by tkurbad** [comment]
@mkconel fperms simply doesn't support wildcards in this manner.

Changing the line:
```fperms 0755 /var/lib/gitlab-gitaly/ruby/bin/*```
to
```fperms 0755 /var/lib/gitlab-gitaly/ruby/bin/{gitaly-ruby,ruby-cd}```

fixes the problem for me.

**Comment by fritteli** [comment]
Strange, it installed without problems for me. Perhaps we are using a different version of portage, or some different configuration of emerge-sandboxing? I don't know.
FWIW, I'll implement @tkurbad 's change and hope it helps.

**Comment by fritteli** [comment]
Done in ebuild 0.43.1.

**Comment by fritteli** [comment]
Oh, and thanks for reporting, and sorry for the (very, very) long delay 😇
