### ISSUE TITLE
www-servers/gitlab-gitaly - Missing dependency for bundler

### ISSUE THREAD

**Issue by g0dsCookie** [fritteli/gentoo-overlay#51]
www-servers/gitlab-gitaly is fails to build because bundler is missing as dependency:

`>>> Compiling source in /var/portage/tmp/portage/www-servers/gitlab-gitaly-0.38.0-r1/work/gitlab-gitaly-0.38.0 ...
make -j9 
if test -z "" ; then cd ruby && bundle config --local path vendor/bundle; fi
/bin/sh: bundle: command not found`

Please add `dev-ruby/bundler` to DEPENDS.

Workaround (without changing the ebuild): `emerge -1av dev-ruby/bundler`

**Comment by fritteli** [comment]
Fixed in 0.43.1 (finally! Thanks for reporting.)
