### ISSUE TITLE
gitlab-runner

### ISSUE THREAD

**Issue by necrose99** [fritteli/gentoo-overlay#53]
https://download.docker.com/linux/static/stable/aarch64/

IUSE="-docker-build"  docker is mildly stale but built ...  however since on iot device works well...
hoping to upgrade iot board to one that can run docker etc.. ie 4-16 gigs .. 

anycase trying to build [MottainaiCI](https://github.com/MottainaiCI)  
agent requiring the depend.. albeit with a good dose of hacks... 

echo "*/*::fritteli ~arm64" >> /etc/portage/package.accept_keywords/fritteli

[gitlab-runner-10.3.1-1.xpak.zip](https://github.com/fritteli/gentoo-overlay/files/1998005/gitlab-runner-10.3.1-1.xpak.zip) wich is a working result..  not sure if its the ebuild or upstream..

**Comment by fritteli** [comment]
The ebuild is no longer part of this repository.
