### ISSUE TITLE
Not an issue, but a request - can we have x86 builds again?

### ISSUE THREAD

**Issue by Bigun** [fritteli/gentoo-overlay#56]
Please?  :)

**Comment by fritteli** [comment]
I'd be happy to provide that, but - well, what package are you referring to? 😄

**Comment by Bigun** [comment]
My apologies - duplicati-bin

LOL

**Comment by fritteli** [comment]
Sorry for not responding earlier, but we've just moved and until we have the new apartement more or less set up I'm afraid I don't have time for updating the ebuild. I hope you can wait a few more days ... thanks for your understanding!

**Comment by fritteli** [comment]
I finally added the ~x86 keyword. It's pushed to my Github repo, but perhaps it takes a day or so to synchronize with the official Gentoo mirror repository.
