### ISSUE TITLE
No manifest for scalix-community-11.3.0.ebuild

### ISSUE THREAD

**Issue by Kami-no** [fritteli/gentoo-overlay#7]
Updating cache for overlay: fritteli * Manifest not found for '/var/lib/layman/fritteli/net-misc/scalix-community/scalix-community-11.3.0.ebuild'

Not using it. Just don't like warnings =)

**Comment by fritteli** [comment]
Thanks for pointing this out. That ebuild was never really used, so I just deleted it.
