### ISSUE TITLE
www-apps/gitlabhq-7.7.2: No authentication methods configured

### ISSUE THREAD

**Issue by Kami-no** [fritteli/gentoo-overlay#8]
Upgraded to 7.7.2 and now unable to login...
Solutions from https://github.com/gitlabhq/gitlabhq/issues/8589 unacceptable. Commands not found...

**Comment by fritteli** [comment]
What version did you upgrade from?

**Comment by Kami-no** [comment]
I'm not sure. But downgrade to 7.7.1 didn't helped. Downgrading to 7.6.2 now.

**Comment by fritteli** [comment]
I still have version 7.2.1 installed on my local PC. I'll perform an upgrade to 7.7.1 and see what happens. On my server, I didn't have any problems after the upgrade from 7.6.2 to 7.7.1, so it's hard for me to find out what could've gone wrong on your machine.

**Comment by Kami-no** [comment]
I'll make a backup and try once more.

**Comment by fritteli** [comment]
I have no idea if that helps, but in my case, I had user-signup enabled when I upgraded from 7.6.2 to 7.7.1.
How did your second attempt go?

**Comment by fritteli** [comment]
Could you try installing gitlabhq 7.8? I'm not sure if it will help, but it's a new version, so you might as well give it a try ...

**Comment by Kami-no** [comment]
7.7.1 same
7.8.1 500 We're sorry, but something went wrong.

**Comment by Kami-no** [comment]
https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/7.7-to-7.8.md
https://github.com/gitlabhq/gitlabhq/issues/8864

cd /opt/gitlab-6
bundle exec rake db:migrate RAILS_ENV=production
bundle exec rake assets:clean assets:precompile cache:clear RAILS_ENV=production
bundle exec rake gitlab:env:info RAILS_ENV=production
bundle exec rake gitlab:check RAILS_ENV=production

bundle exec rake gitlab:satellites:create RAILS_ENV=production

SOLVED.

**Comment by broth-eu** [comment]
I had the same issue using version 7.7: when I go to GitLab's landing page I cannot login because I only get the message "No authentication methods configured.". Unfortunatelly, upgrading to 7.8 and executing your commands didn't solve my problem. According to db:migrate:status all database migrations have been performed successfully.

Does anyone have some further ideas?
