### ISSUE TITLE
gitlabhq: error bundling timfel-krb5-auth (0.8.3)

### ISSUE THREAD

**Issue by xificurk** [fritteli/gentoo-overlay#9]
Hi, I'm having trouble installing gilabhq on up-to-date stable amd64 system (gitlabhq was not installed before, so it's a fresh new install). Bundler fails in install phase of the ebuild with:
> An error occurred while installing timfel-krb5-auth (0.8.3), and Bundler cannot continue.

Complete build log is here: https://www.dropbox.com/s/fnuhlux5ht95erd/gitlabhq.build.log?dl=0

I would appreciate any ideas about what the problem might be. Anyway, thanks for the ebuild!

**Comment by xificurk** [comment]
Ok, so it seems I've hit timfel/krb5-auth#8, which is kind of bummer, because I must use heimdal and not mit-krb5 implementation, because I need openldap with smbkrb5passwd.
I would be ok with disabling kerberos support in gitlab, but it seems there is no easy way to do it. Unless anyone suggests a workaround how to get gitlabhq play nicely with heimdal, I would suggest adding it as a blocker to the ebuild.

**Comment by fritteli** [comment]
Added app-crypt/heimdal as blocking dependency to all ebuilds >=7.7
